export const SET_WINDOW_SIZE = "SET_WINDOW_SIZE";
export const IS_MOBILE_WINDOW = "IS_MOBILE_WINDOW";
export const ENTER_AUTHENTICATION_PAGE = "ENTER_AUTHENTICATION_PAGE";
export const EXIT_AUTHENTICATION_PAGE = "EXIT_AUTHENTICATION_PAGE";
export const ACCOUNT_TYPE = "ACCOUNT_TYPE";